name: test_google_mlkit
description: "Google ML Kit"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4


##################
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8    
  camera: ^0.11.3
  camera_android: ^0.10.10+14
  camera_avfoundation: ^0.9.23
  google_mlkit_face_detection: ^0.13.2
  google_mlkit_commons: 
  path_provider: ^2.1.5
  path: ^1.9.1
  image_picker: ^1.2.1


####################
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^6.0.0

####################
flutter:
  uses-material-design: true
  assets:
    - assets/